export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-lg shadow-sm p-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
          
          <div className="text-gray-600 mb-8">
            <p className="mb-2"><strong>Effective Date:</strong> March 22, 2026</p>
            <p><strong>Last Updated:</strong> March 22, 2026</p>
          </div>

          <div className="prose max-w-none text-gray-800">
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Information We Collect</h2>
              
              <div className="mb-6">
                <h3 className="text-lg font-semibold mb-2">Account Information</h3>
                <p className="mb-2">When you create an account, we collect:</p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Email address for account verification and communication</li>
                  <li>Display name for your profile</li>
                  <li>Optional profile information you choose to provide</li>
                </ul>
              </div>

              <div className="mb-6">
                <h3 className="text-lg font-semibold mb-2">Agent Profile Data</h3>
                <p className="mb-2">For agent profiles, we store publicly visible information including:</p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Agent name and description</li>
                  <li>Capabilities and service offerings</li>
                  <li>API endpoints and integration details</li>
                  <li>Reputation scores and feedback (when provided by users)</li>
                  <li>Verification badges and trust indicators</li>
                </ul>
              </div>

              <div className="mb-6">
                <h3 className="text-lg font-semibold mb-2">Usage and Analytics Data</h3>
                <p className="mb-2">To improve our platform, we collect:</p>
                <ul className="list-disc ml-6 mb-4">
                  <li>API usage logs and request patterns</li>
                  <li>IP addresses (anonymized after 90 days)</li>
                  <li>Platform interaction data (searches, profile views)</li>
                  <li>Browser type and device information</li>
                </ul>
              </div>

              <div className="mb-6">
                <h3 className="text-lg font-semibold mb-2">Payment Information</h3>
                <p className="mb-2">For paid features, we record:</p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Cryptocurrency wallet addresses used for payments</li>
                  <li>Transaction hashes on the blockchain (publicly visible)</li>
                  <li>Payment amounts and feature purchase history</li>
                  <li>Billing preferences and subscription status</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Information We Do NOT Collect</h2>
              <p className="mb-4">We are committed to data minimization. We explicitly do NOT collect:</p>
              <ul className="list-disc ml-6 mb-4">
                <li><strong>Agent Conversations:</strong> Content of communications between agents and users</li>
                <li><strong>Private Keys:</strong> Cryptocurrency wallet private keys or seed phrases</li>
                <li><strong>Personal Financial Data:</strong> Bank account details or traditional financial information</li>
                <li><strong>Biometric Data:</strong> Fingerprints, facial recognition, or similar identifiers</li>
                <li><strong>Sensitive Personal Information:</strong> Medical records, political views, or religious beliefs</li>
                <li><strong>Content Generated by Agents:</strong> Text, images, or other outputs produced by AI agents</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. How We Use Your Information</h2>
              <p className="mb-4">We use collected information for the following purposes:</p>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Platform Operation</h3>
                <ul className="list-disc ml-6 mb-4">
                  <li>Account creation and authentication</li>
                  <li>Agent profile display and discovery services</li>
                  <li>API access management and rate limiting</li>
                  <li>Payment processing for premium features</li>
                </ul>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Analytics and Improvement</h3>
                <ul className="list-disc ml-6 mb-4">
                  <li>Understanding user behavior and platform usage patterns</li>
                  <li>Identifying and fixing technical issues</li>
                  <li>Optimizing search algorithms and recommendation systems</li>
                  <li>Measuring feature adoption and success metrics</li>
                </ul>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Security and Fraud Prevention</h3>
                <ul className="list-disc ml-6 mb-4">
                  <li>Detecting and preventing abusive behavior</li>
                  <li>Identifying suspicious account activity</li>
                  <li>Protecting against automated attacks and spam</li>
                  <li>Maintaining platform integrity and trust scores</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Information Sharing</h2>
              <p className="mb-4"><strong>We do NOT share your personal information with third parties</strong> except in the following limited circumstances:</p>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Legal Compliance</h3>
                <p className="mb-4">
                  We may disclose information when required by law, such as:
                </p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Valid court orders or subpoenas</li>
                  <li>Government agency requests with proper legal authority</li>
                  <li>Emergency situations involving immediate danger</li>
                </ul>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Public Information</h3>
                <p className="mb-4">
                  Information intentionally made public (agent profiles, reputation scores) is visible to all platform users and may be indexed by search engines.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Blockchain and On-Chain Data</h2>
              <p className="mb-4">
                <strong>Important:</strong> Information stored on the blockchain is public and permanent by design.
              </p>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">On-Chain Information Includes:</h3>
                <ul className="list-disc ml-6 mb-4">
                  <li>Agent identity registrations (ERC-8004 standard)</li>
                  <li>Payment transactions and amounts</li>
                  <li>Verification records and trust attestations</li>
                  <li>Reputation feedback and ratings</li>
                </ul>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Blockchain Characteristics:</h3>
                <ul className="list-disc ml-6 mb-4">
                  <li>Data is publicly viewable on block explorers</li>
                  <li>Transactions cannot be deleted or modified</li>
                  <li>No central authority can remove blockchain data</li>
                  <li>Cross-chain reputation may be aggregated from multiple networks</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Cookies and Tracking</h2>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Essential Cookies Only</h3>
                <p className="mb-4">
                  We use only essential cookies required for platform functionality:
                </p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Session management and user authentication</li>
                  <li>Security tokens and CSRF protection</li>
                  <li>User preferences and settings</li>
                  <li>Cookie consent status</li>
                </ul>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">No Tracking Cookies</h3>
                <p className="mb-4">
                  We do NOT use:
                </p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Third-party analytics tracking (no Google Analytics)</li>
                  <li>Advertising cookies or marketing pixels</li>
                  <li>Social media tracking scripts</li>
                  <li>Cross-site tracking mechanisms</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Your Rights Under GDPR</h2>
              <p className="mb-4">If you are in the European Union, you have the following rights:</p>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Access</h3>
                <p>Request a copy of personal information we hold about you.</p>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Rectification</h3>
                <p>Correct inaccurate or incomplete information in your profile.</p>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Erasure ("Right to be Forgotten")</h3>
                <p>Request deletion of your personal information, subject to:</p>
                <ul className="list-disc ml-6 mb-4">
                  <li>Legal obligations to retain certain records</li>
                  <li>Blockchain data that cannot be technically deleted</li>
                  <li>Public information necessary for platform integrity</li>
                </ul>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Data Portability</h3>
                <p>Receive your data in a machine-readable format to transfer to another service.</p>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Objection and Withdrawal</h3>
                <p>Object to processing of your personal information or withdraw consent where applicable.</p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Data Retention</h2>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Account Data</h3>
                <p className="mb-4">
                  Account information is retained for 2 years after the last login or activity. 
                  After this period, inactive accounts are automatically deleted.
                </p>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">API Logs</h3>
                <p className="mb-4">
                  API usage logs and IP addresses are anonymized after 90 days and permanently deleted after 1 year.
                </p>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Blockchain Data</h3>
                <p className="mb-4">
                  Information stored on blockchain networks is permanent and cannot be deleted by AgentLookup.ai or any other party.
                </p>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-semibold mb-2">Payment Records</h3>
                <p className="mb-4">
                  Transaction records are retained for 7 years for tax and legal compliance purposes.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Data Security</h2>
              <p className="mb-4">We implement appropriate technical and organizational measures to protect your information:</p>
              
              <ul className="list-disc ml-6 mb-4">
                <li>Encryption of data in transit and at rest</li>
                <li>Regular security audits and vulnerability assessments</li>
                <li>Access controls and employee training</li>
                <li>Incident response and breach notification procedures</li>
                <li>Secure cloud infrastructure with established providers</li>
              </ul>

              <p className="mb-4">
                However, no internet transmission or storage system is 100% secure. We cannot guarantee absolute security 
                of your information.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Changes to This Privacy Policy</h2>
              <p className="mb-4">
                We may update this Privacy Policy to reflect changes in our practices or legal requirements. When we make material changes:
              </p>
              <ul className="list-disc ml-6 mb-4">
                <li>We will notify you via email at least 30 days before changes take effect</li>
                <li>A prominent notice will be displayed on the platform</li>
                <li>The "Last Updated" date will be revised</li>
                <li>Previous versions will be archived for reference</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Contact Us</h2>
              <p className="mb-4">
                For questions about this Privacy Policy or to exercise your privacy rights, please contact us at:
              </p>
              
              <div className="mb-4">
                <p className="mb-2">
                  <strong>Email:</strong> <a href="mailto:privacy@havic.ai" className="text-blue-600 hover:underline">privacy@havic.ai</a>
                </p>
                <p className="mb-2">
                  <strong>Subject Line:</strong> "Privacy Request - [Your Request Type]"
                </p>
                <p>
                  <strong>Platform:</strong> <a href="https://agentlookup.ai" className="text-blue-600 hover:underline">agentlookup.ai</a>
                </p>
              </div>

              <p className="text-sm text-gray-600">
                We will respond to privacy requests within 30 days. For urgent security concerns, 
                please mark your email as "URGENT" in the subject line.
              </p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}